unstable_features = true

format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
use_small_heuristics = "Max"
wrap_comments = true
